// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxCizwD2HI0FNh587GILP7bnZKsmPajFY',
    appId: '1:900712761830:web:a2b99bc0df870d992f6e27',
    messagingSenderId: '900712761830',
    projectId: 'fitbud-46f70',
    authDomain: 'fitbud-46f70.firebaseapp.com',
    storageBucket: 'fitbud-46f70.firebasestorage.app',
    measurementId: 'G-ZTQ0GZWZS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-qlTQfT7LSxai6Ak-lolUYupFRtvWmls',
    appId: '1:900712761830:android:d5a3ff698713767c2f6e27',
    messagingSenderId: '900712761830',
    projectId: 'fitbud-46f70',
    storageBucket: 'fitbud-46f70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8QqFPlaxl1V9PJ7l1r_kz8O-vR0mCiBk',
    appId: '1:900712761830:ios:cbba31fb5629ef262f6e27',
    messagingSenderId: '900712761830',
    projectId: 'fitbud-46f70',
    storageBucket: 'fitbud-46f70.firebasestorage.app',
    iosBundleId: 'com.example.fitbud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8QqFPlaxl1V9PJ7l1r_kz8O-vR0mCiBk',
    appId: '1:900712761830:ios:cbba31fb5629ef262f6e27',
    messagingSenderId: '900712761830',
    projectId: 'fitbud-46f70',
    storageBucket: 'fitbud-46f70.firebasestorage.app',
    iosBundleId: 'com.example.fitbud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxCizwD2HI0FNh587GILP7bnZKsmPajFY',
    appId: '1:900712761830:web:db28f3b99da14a702f6e27',
    messagingSenderId: '900712761830',
    projectId: 'fitbud-46f70',
    authDomain: 'fitbud-46f70.firebaseapp.com',
    storageBucket: 'fitbud-46f70.firebasestorage.app',
    measurementId: 'G-EYHLRKJBF6',
  );

}