// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDatHFvLjr47xsMUOhJ-rgKOvzekIGC1Uk',
    appId: '1:6903241866:web:80d8c0ae28d7d6d9696173',
    messagingSenderId: '6903241866',
    projectId: 'fitbudpk',
    authDomain: 'fitbudpk.firebaseapp.com',
    storageBucket: 'fitbudpk.firebasestorage.app',
    measurementId: 'G-Q5M50GRZ7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdHsdDmvPtlJCWlZwgAsu8NWfU3hvV2kg',
    appId: '1:6903241866:android:de08f55801f6c4be696173',
    messagingSenderId: '6903241866',
    projectId: 'fitbudpk',
    storageBucket: 'fitbudpk.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcaqxg6GMjaG7rnam9ewCncf0yH8xJk_I',
    appId: '1:6903241866:ios:afa51df718d2d6c8696173',
    messagingSenderId: '6903241866',
    projectId: 'fitbudpk',
    storageBucket: 'fitbudpk.firebasestorage.app',
    iosBundleId: 'com.fitbudpk.fitbud',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8QqFPlaxl1V9PJ7l1r_kz8O-vR0mCiBk',
    appId: '1:900712761830:ios:cbba31fb5629ef262f6e27',
    messagingSenderId: '900712761830',
    projectId: 'fitbud-46f70',
    storageBucket: 'fitbud-46f70.firebasestorage.app',
    iosBundleId: 'com.fitbudpk.fitbud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxCizwD2HI0FNh587GILP7bnZKsmPajFY',
    appId: '1:900712761830:web:db28f3b99da14a702f6e27',
    messagingSenderId: '900712761830',
    projectId: 'fitbud-46f70',
    authDomain: 'fitbud-46f70.firebaseapp.com',
    storageBucket: 'fitbud-46f70.firebasestorage.app',
    measurementId: 'G-EYHLRKJBF6',
  );

}
